### ISSUE TITLE
[BUG]: trying to install on an rpi running debian 11: mongodb piece is failing

### ISSUE THREAD

**Issue by the-bort-the** [azukaar/Cosmos-Server#11]
### What happened?

When I run try to run the docker compose up -d I see the following error in the db containers. I cam able to start the first `cosmos-server` container and try to run the wizard. The docker daemon is started, but when I try to have it create the database, below is the error I receive.

WARNING: MongoDB requires ARMv8.2-A or higher, and your current system does not appear to implement any of the common features for that!

### What should have happened?

Seems like it was trying to created the recommended database 

### How to reproduce the bug?

copy the docker-compose.yml and start the cosmos-server container. Once started, follow the wizard to the create the database

### Relevant log output

```shell
/usr/local/bin/docker-entrypoint.sh: line 416:    28 Illegal instruction     "${mongodHackedArgs[@]}" --fork

WARNING: MongoDB requires ARMv8.2-A or higher, and your current system does not appear to implement any of the common features for that!
  applies to all versions ≥5.0, any of 4.4 ≥4.4.19, and any of 4.2 ≥4.2.19
  see https://jira.mongodb.org/browse/SERVER-71772
  see https://jira.mongodb.org/browse/SERVER-55178
  see also https://en.wikichip.org/wiki/arm/armv8#ARMv8_Extensions_and_Processor_Features
  see also https://github.com/docker-library/mongo/issues/485#issuecomment-970864306
```

### System details

$ hostnamectl:
   Static hostname: raspberrypi
         Icon name: computer
        Machine ID: bb7a41ee9d1f4aa48e114ee01eaf4410
           Boot ID: c097b363e631490fb6fdf53ee63c992c
  Operating System: Debian GNU/Linux 11 (bullseye)
            Kernel: Linux 6.1.21-v8+
      Architecture: arm64

**Comment by azukaar** [comment]
This is an issue with MongoDB not being compatible with your CPU. Unfortunately not much I can do about it. Although, you might have better luck trying with MongoDB 4, which is more compatible with older CPU. There's a bit about it in the doc. You can try with this docker-compose provided by another user on the Discord. Just remember to change the images for ARM ones

```
version: '3.3'
services:
 cosmos-server:
    image: 'azukaar/cosmos-server:latest'
    ports:
        - '88:80'
        - '448:443'
    container_name: cosmos-server
    hostname: cosmos-server
    environment:
        - COSMOS_HOSTNAME:'192.168.1.210'
        - COSMOS_MONGODB:'mongodb://USERNAME:PASSWORD@cosmo-mongo'

    restart: always
    volumes:
        - '/var/run/docker.sock:/var/run/docker.sock'
        - '/share/docker-apps/cosmos-server/config:/config'
    networks:
      - cosmos

 cosmo-mongo:
    image: mongo:4.4
    container_name: cosmos-mongo-uni
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: USERNAME
      MONGO_INITDB_ROOT_PASSWORD: PASSWORD
    volumes:
      - '/share/docker-apps/cosmos-server/cosmos-db/data:/data/db'
      - '/share/docker-apps/cosmos-server/cosmos-db/config:/data/configdb '
    networks:
      - cosmos

networks:
   cosmos:
     name: cosmos-db
     external: false
```
