### ISSUE TITLE
[BUG]: Database is never created.

### ISSUE THREAD

**Issue by PassiveLemon** [azukaar/Cosmos-Server#24]
### What happened?

After the docker section of the setup shows as successful, the database portion will get stuck on connecting, even if the option to create a database is selected.

### What should have happened?

According to the docs, it should create its own database in around 20-30 seconds.

### How to reproduce the bug?

1. Create container using docker-compose
2. Get to the database portion of the setup
3. Observe

### Relevant log output

```shell
It will spam this into the docker log:

2023/06/07 13:46:25 [INFO] SmartShield: Request received
2023/06/07 13:46:25 [INFO] API: Status
2023/06/07 13:46:25 [INFO] (Re) Connecting to the database...
2023/06/07 13:46:25 [ERROR] Status: Database error : error parsing uri: scheme must be "mongodb" or "mongodb+srv"

```

### Other details

```
 cosmos:
    image: azukaar/cosmos-server:latest
    container_name: cosmos
    restart: 'always'
    ports:
      - 23080:80/tcp
      - 22443:443/tcp
    volumes:
      - /home/docker/Containers/Test/Cosmos:/config
      - /var/run/docker.sock:/var/run/docker.sock
 ```
It also does the same thing when running with docker run

### System details

- OS: NixOS 23.05 (Linux)
- Browser: Firefox
- Version: 112.0.2
