### ISSUE TITLE
[BUG]: Docker Compose import ignores hostname

### ISSUE THREAD

**Issue by plangin** [azukaar/Cosmos-Server#289]
### What happened?

When I import a docker compose, the hostname is ignored.

It could look like this:

```
services:
  pihole:
    container_name: pihole
    environment:
      FTLCONF_LOCAL_IPV4: 192.168.178.10
      TZ: Europe/Berlin
    hostname: pihole
```

Instead the hostname pihole, Cosmos Server creates some hostname like 97eb67d37625

Excerpt of generated Cosmos Compose:

```
      "entrypoint": "/s6-init",
      "hostname": "97eb67d37625",
      "network_mode": "cosmos-pihole-default",
```

### What should have happened?

Create a new container with the hostname pihole.

### How to reproduce the bug?

1. Go to 'ServApps'
2. Click on 'Import Compose File'
3. Import some Docker Compose file with hostname information.

### System details

- Cosmos v0.15.7

**Comment by azukaar** [comment]
hostname is forced to be the name of the container because otherwise it makes a lot of things confusing - that is the intended behaviour

**Comment by plangin** [comment]
> send the compose you are using so I can try reproduce the issue?

Sure:

```
services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:2 # Version 2 für TeslaMate
    hostname: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
```

When importing this Docker Compose, it looks on the next screen in Cosmos Compose that the hostname is recognized correctly and will applied to the container:

```
{
  "services": {
    "mosquitto": {
      "container_name": "mosquitto",
      "image": "eclipse-mosquitto:2",
      "hostname": "mosquitto",
      "restart": "unless-stopped",
      "ports": [
        "1883:1883"
      ],
      "network_mode": "cosmos-mosquitto-default"
    }
  },
  "networks": {
    "cosmos-mosquitto-default": {}
  }
}
```

But on the end, the resulting hostname was d329d1f3a41a, not mosquito.

Technical background:

I prefer to use speaking and static hostnames, so I can connect effortless to them. In that example I connect Home Assistant and Zigbee2MQTT to the host 'mosquito'.
