### ISSUE TITLE
[BUG]: Cosmos-Compose does not persist the runtime option

### ISSUE THREAD

**Issue by ryan-schubert** [azukaar/Cosmos-Server#290]
### What happened?

I am trying to configure Jellyfin to use my GPU for transcoding. Part of that involves specifying a runtime in my jellyfin compose file, like this for example ([from Jellyfin docs](https://jellyfin.org/docs/general/administration/hardware-acceleration/nvidia#official-docker)):

```
version: '3'
services:
  jellyfin:
    image: jellyfin/jellyfin
    user: 1000:1000
    network_mode: 'host'
    volumes:
      - /path/to/config:/config
      - /path/to/cache:/cache
      - /path/to/media:/media
    runtime: nvidia

```
After saving though, the runtime option disappears.

### What should have happened?

The runtime configuration specified is respected and used

### How to reproduce the bug?

Try to specify a runtime via cosmos-compose

### System details

- OS: debian
