### ISSUE TITLE
[BUG]: Wrong nickname or password. Try again or try resetting your password

### ISSUE THREAD

**Issue by riczescaran** [azukaar/Cosmos-Server#30]
### What happened?

This problem keeps happening even though I am putting the correct password.

### What should have happened?

When encountering this problem It should ask for password reset function. 

### How to reproduce the bug?

Configured my /etc/hosts

`127.0.0.1 homelab.local`

My docker compose file:

```
version: "3.3"
services:
    cosmos-server:
        ports:
            - "80:80"
            - "443:443"
        container_name: cosmos-server
        hostname: cosmos-server
        restart: always
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
            - "./config:/config"
            - "./host:/mnt/host"
        image: "azukaar/cosmos-server:latest"
```

Steps I did when setting up the cosmos server:
1. Automatically create a secure database (recommended)
2. Use HTTP only (not recommended)
3. Set hostname homelab.local. I checked "Use Wildcard Certificate for *.homelab.local" and clicked update
4. Supplied username and password (I used lastpass password generator)

### Other details

HTTP response:
```
{
    "status": "error",
    "message": "User Logging Error",
    "code": "UL001"
}
```

### System details

- OS: Windows 10 Pro
- Browser Microsoft Edge Version 114.0.1823.43 (Official build) (64-bit)]
- Docker version 4.20.1
