### ISSUE TITLE
[FEAT]: Gluetun Integration under ServApps

### ISSUE THREAD

**Issue by genefyx** [azukaar/Cosmos-Server#346]
### Feature Description

The ability provide a Wireguard/VPN connection, and tie containers to run under Glutun.

**Comment by kolossboss** [comment]
Hi,

I’d like to use Gluetun as well.

Currently, I’ve configured all apps in a single Docker Compose file to route traffic through the Gluetun network. This setup works great! However, I’m curious if it’s possible to configure or use a similar setup with Cosmos.

```
version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 37801:8989/tcp # Sonarr
    volumes:
      - /Volumes/PlexData/Docker/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=openvpn
      - OPENVPN_CUSTOM_CONFIG=/gluetun/xxxx
      - TZ=DE
      - OPENVPN_USER=xxxxxx
      - OPENVPN_PASSWORD=xxxxxx
      - HTTPPROXY=on

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    network_mode:  "service:gluetun"
    environment:
      - PUID=501
      - PGID=20
      - TZ=DE
    volumes:
      - /Volumes/Docker/Sonarr:/config
    restart: unless-stopped
```
