### ISSUE TITLE
[GUIDE]: How to use cron in Nextcloud

### ISSUE THREAD

**Issue by Arturro43** [azukaar/Cosmos-Server#62]
Hello,

So I wanted to use cron as background job for Nextcloud, but I didn't know how. After some research and troubleshooting I've came up with the solution.

Setup Nextcloud as always, then go to ServApps in your Cosmos webapp, click Import Compose File.

Paste this:

<details>

```yaml
version: '3.7'

services:
  app:
    image: nextcloud:apache

  cron:
    image: rcdailey/nextcloud-cronjob
    restart: always
    network_mode: none
    depends_on:
    - app
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /etc/localtime:/etc/localtime:ro
    environment:
    - NEXTCLOUD_CONTAINER_NAME=Nextcloud
    - NEXTCLOUD_CRON_MINUTE_INTERVAL=5
  ```

</details>

Then go to Details of this newly created "container", Storage and add volumes used by your Nextcloud (just copy and paste Volume and Bind):
![image](https://github.com/azukaar/Cosmos-Server/assets/10798277/c0a96de9-2a84-49f2-bf41-8b3e0cac4778)

Done. I've been learning for 2 days now (since the day I installed Cosmos on my server), so probably someone can modify this compose to include default storage used by Nextcloud.
