### ISSUE TITLE
[GUIDE]: How to setup Send instance

### ISSUE THREAD

**Issue by Arturro43** [azukaar/Cosmos-Server#63]
[Send](https://github.com/timvisee/send) is a fork of Mozilla's [Firefox Send](https://github.com/mozilla/send). It's perfect for sharing files with friends with ease.

Default docker-compose.yml just simply doesn't work, so I've created my own (do not copy and paste, this needs to be reconfigured!):

<details>

```yaml
version: "3"

services:
  nginx-proxy:
    container_name: nginx-proxy
    image: 'jwilder/nginx-proxy:alpine'
    restart: always
    ports:
      - 'setunusedporthere:80'
      - 'setunusedporthere:443'
    environment:
      - DEFAULT_HOST=HERE.IS.YOUR.DOMAIN.TLD
      - HSTS=off
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - proxy-certs:/etc/nginx/certs:ro
      - proxy-vhost:/etc/nginx/vhost.d
      - proxy-html:/usr/share/nginx/html
  proxy-letsencrypt:
    image: 'jrcs/letsencrypt-nginx-proxy-companion'
    restart: always
    environment:
      - DEFAULT_EMAIL=HEREGOESYOUR@EMAIL.COM
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - NGINX_DOCKER_GEN_CONTAINER=nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - proxy-certs:/etc/nginx/certs
      - proxy-vhost:/etc/nginx/vhost.d
      - proxy-html:/usr/share/nginx/html
  send:
    image: 'ghcr.io/xavion-lux/send:latest' #this image supports arm64
    restart: always
    ports:
      - '1443:1443'
    volumes:
      - ./data/send:/send
    environment:
      - VIRTUAL_HOST=HERE.IS.YOUR.DOMAIN.TLD
      - VIRTUAL_PORT=1443
      - DHPARAM_GENERATION=false
      - LETSENCRYPT_HOST=HERE.IS.YOUR.DOMAIN.TLD
      - LETSENCRYPT_EMAIL=HEREGOESYOUR@EMAIL.COM
      - NODE_ENV=development
      - BASE_URL=HERE.IS.YOUR.DOMAIN.TLD
      - PORT=1443
      - FILE_DIR=/send
  proxy-certs:
  proxy-vhost:
  proxy-html:
```

</details>

These settings are for local storage only, you can try to change it to support S3 using variables from default [docker-compose](https://github.com/timvisee/send-docker-compose)
  
After that you go to your ssh (preferably as root) then cd to /usr/ and execute command:
 
`chown 1000:1000 data/send`

Done.
